<?php 

/**
 * Implementation of hook_menu.
 */
function edully_front_page_menu () {
  $items['frontpage'] = array(
    'title' => 'Learning Through Conversations',
    'description' => t('Generates front page for Edully sites'),
    'page callback' => 'edully_front_page_frontpage',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/*
 * Implementaiton of hook_init().
 */
function edully_front_page_init() {
  drupal_add_js(drupal_get_path('module', 'edully_front_page') . "/edully_front_page.js");
}
/*
 * Generates front page for Edully sites
 */
function edully_front_page_frontpage() {
  global $user;
  if (!$user->uid) { // User is anonymous.
    $out .= edully_front_page_marketing_stuff();
    
    // Login form
    $out .= drupal_get_form('user_login');
    return $out;  
  }
  else {
    $out .= "<h2>Latest activity in my groups</h2>";
    $out .= views_embed_view('eduglu_recent_activity', $display_id = 'page');
    return $out;
  }
  
}

function edully_front_page_marketing_stuff() {
  $out = <<<TABLE
  <table id='front-page-marketing'>
  <tr>
  <td id="front-teachers">
    <div>
      <h2>Teachers</h2>
        <ul>
          <li>Incorporate active learning in your classroom</li>
          <li>Integrate student-to-student learning groups</li>
          <li>Build student-driven knowledge repositories for your topic</li>
        </ul>
        <br />
        <p class="join-now"><a href="user">Create a class group now!</a></p>
    </div>
  </td>
    
  <td id="front-students">
    <div>
      <h2>Students</h2>
        <ul>
          <li>Join <a href="groups">groups</a> for your interests</li>
          <li>Get help on projects</li>
          <li>Connect to people in your major (<a href="content/island-major-groups">See if there's a group yet for your major</a>)</li>
        </ul>
        <br />
        <br />
        <br />
        <p class="join-now"><a href="user">Join now with your Route Y ID!</a></p>
    </div>
  </td>
  
  <td id="front-alumni">
    <div>
      <h2>Alumni</h2>
        <ul>
          <li>Connect with friends from school</li>
          <li>Keep up-to-date on latest advances in your field</li>
          <li>Find students to recruit to your firm</li>
        </ul>
        <br />
        <br />
        <br />
        <p class="join-now"><a href="user">Join now with your Route Y ID!</a></p>
    </div>
  </td>
  </tr>
  </table>
TABLE;
  
  return $out;
}
